#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEST_ROOT="${PKG_DIR}/tmp/init-local-test"
NPM_CACHE_DIR="${PKG_DIR}/tmp/npm-cache"

PCI_NAME="${1:-LocalTsPci}"
PROJECT_TYPE="${2:-typescript}"
DESCRIPTION="${3:-Local init test generated by script}"

TARGET_DIR="${TEST_ROOT}/${PCI_NAME}"
rm -rf "${TARGET_DIR}"
mkdir -p "${NPM_CACHE_DIR}"

echo "Packing local @citolab/tspci package..."
PACK_TGZ="$(cd "${PKG_DIR}" && npm pack --silent --cache "${NPM_CACHE_DIR}" | tail -n 1)"
PACK_PATH="${PKG_DIR}/${PACK_TGZ}"
cleanup() {
  rm -f "${PACK_PATH}" 2>/dev/null || true
}
trap cleanup EXIT

echo "Generating project in: ${TARGET_DIR}"
node "${PKG_DIR}/src/cli.js" init \
  --no-install \
  --force \
  --path "${TEST_ROOT}" \
  --name "${PCI_NAME}" \
  --description "${DESCRIPTION}" \
  --project-type "${PROJECT_TYPE}"

echo ""
echo "Pointing generated project to local @citolab/tspci package..."
node -e "
  const fs = require('fs');
  const path = require('path');
  const pkgPath = process.argv[1];
  const localDep = process.argv[2];
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  pkg.devDependencies = pkg.devDependencies || {};
  pkg.devDependencies['@citolab/tspci'] = localDep;
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
" "${TARGET_DIR}/package.json" "file:${PACK_PATH}"

echo ""
echo "Generated files:"
find "${TARGET_DIR}" -maxdepth 3 -type f | sort

EXPECTED_FILE="${TARGET_DIR}/src/index.ts"
if [[ "${PROJECT_TYPE}" == "javascript" ]]; then
  EXPECTED_FILE="${TARGET_DIR}/src/index.js"
fi
if [[ "${PROJECT_TYPE}" == "preact+tailwind" ]]; then
  EXPECTED_FILE="${TARGET_DIR}/src/index.tsx"
fi

if [[ ! -f "${EXPECTED_FILE}" ]]; then
  echo ""
  echo "ERROR: expected entry file not found: ${EXPECTED_FILE}" >&2
  exit 1
fi

echo ""
echo "Installing dependencies in generated project..."
(cd "${TARGET_DIR}" && npm install --cache "${NPM_CACHE_DIR}")

echo ""
echo "Running production build smoke test..."
node -e "
  const { spawnSync } = require('child_process');
  const targetDir = process.argv[1];
  const result = spawnSync('npm', ['run', 'prod'], {
    cwd: targetDir,
    stdio: 'inherit',
    timeout: 180000
  });
  if (result.error) {
    console.error(result.error.message);
    process.exit(1);
  }
  process.exit(result.status ?? 1);
" "${TARGET_DIR}"

DIST_JS="${TARGET_DIR}/dist/index.js"
if [[ ! -f "${DIST_JS}" ]]; then
  echo ""
  echo "ERROR: expected build output not found: ${DIST_JS}" >&2
  exit 1
fi

DIST_TYPES="${TARGET_DIR}/dist/index.d.ts"
if [[ ! -f "${DIST_TYPES}" ]]; then
  echo ""
  echo "ERROR: expected type output not found: ${DIST_TYPES}" >&2
  exit 1
fi

echo ""
echo "OK: found expected entry file: ${EXPECTED_FILE}"
echo "OK: production build output exists: ${DIST_JS}"
echo "OK: production type output exists: ${DIST_TYPES}"
